"""user role

Revision ID: 9e876cac05dd
Revises: 546afaf23d23
Create Date: 2020-06-09 01:45:48.171409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e876cac05dd'
down_revision = '546afaf23d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('role', sa.Integer(), nullable=True))
    op.drop_index('ix_user_callendarToken', table_name='user')
    op.drop_index('ix_user_carapiToken', table_name='user')
    op.drop_column('user', 'callendarToken')
    op.drop_column('user', 'carapiToken')
    op.drop_column('user', 'token_expiration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_expiration', mysql.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('carapiToken', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('user', sa.Column('callendarToken', mysql.VARCHAR(length=128), nullable=True))
    op.create_index('ix_user_carapiToken', 'user', ['carapiToken'], unique=True)
    op.create_index('ix_user_callendarToken', 'user', ['callendarToken'], unique=True)
    op.drop_column('user', 'role')
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
