"""user tokens

Revision ID: a328833aafc9
Revises: addb0275d398
Create Date: 2020-05-20 21:29:32.546371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a328833aafc9'
down_revision = 'addb0275d398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('callendarToken', sa.String(), nullable=True))
    op.add_column('user', sa.Column('carapiToken', sa.String(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_callendarToken'), 'user', ['callendarToken'], unique=True)
    op.create_index(op.f('ix_user_carapiToken'), 'user', ['carapiToken'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_carapiToken'), table_name='user')
    op.drop_index(op.f('ix_user_callendarToken'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'email')
    op.drop_column('user', 'carapiToken')
    op.drop_column('user', 'callendarToken')
    # ### end Alembic commands ###
