"""ap intergration

Revision ID: bb0f3918102c
Revises: a328833aafc9
Create Date: 2020-05-24 16:03:54.525556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0f3918102c'
down_revision = 'a328833aafc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_car_name'), 'car', ['name'], unique=True)
    op.add_column('user', sa.Column('face_token', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'face_token')
    op.drop_index(op.f('ix_car_name'), table_name='car')
    # ### end Alembic commands ###
